<div class="w-screen py-16 px-10 md:px-36 overflow-hidden">
    <h1 class="text-center text-3xl underline decoration-blue-600">Kerjasama</h1>
    <div class="flex flex-wrap gap-3 w-full justify-center items-center py-8">
        <x-sponsorImage.index src="/assets/images/akademikom.png"/>
        <x-sponsorImage.index src="/assets/images/ambarukmo.png"/>
        <x-sponsorImage.index src="/assets/images/ameya.png"/>
        <x-sponsorImage.index src="/assets/images/amikom.png"/>
        <x-sponsorImage.index src="/assets/images/ampta.jpg"/>
        <x-sponsorImage.index src="/assets/images/duta.png"/>
        <x-sponsorImage.index src="/assets/images/gmedia.jpg"/>
        <x-sponsorImage.index src="/assets/images/janabadra.png"/>
        <x-sponsorImage.index src="/assets/images/mirota.png"/>
        <x-sponsorImage.index src="/assets/images/msd.png"/>
        <x-sponsorImage.index src="/assets/images/profidana.png"/>
        <x-sponsorImage.index src="/assets/images/pt_time_excelindo_logo.jpeg"/>
        <x-sponsorImage.index src="/assets/images/sejong.jpg"/>
        <x-sponsorImage.index src="/assets/images/semar.jpg"/>
        <x-sponsorImage.index src="/assets/images/seven.png"/>
        <x-sponsorImage.index src="/assets/images/stikom.jpeg"/>
        <x-sponsorImage.index src="/assets/images/uad.png"/>
        <x-sponsorImage.index src="/assets/images/mercubuana.png"/>
        <x-sponsorImage.index src="/assets/images/unjani.png"/>
        <x-sponsorImage.index src="/assets/images/ust.png"/>
        <x-sponsorImage.index src="/assets/images/ut.png"/>
        <x-sponsorImage.index src="/assets/images/utdi.png"/>
        <x-sponsorImage.index src="/assets/images/uty.png"/>
        <x-sponsorImage.index src="/assets/images/maspion.jpeg"/>
    </div>
</div>